
   # i dont know what i am doing 
name: build apk whenever main push
on: 
   push:
    branches:
      - main
          
jobs:  
  build_apk:
      name: "Build release apk"
      runs-on:
        - ubuntu-latest
      steps:
        - name: "Using flutter version"
          uses: subosito/flutter-action@v2
             
        - name: "Build apk --release"
          run: |
            flutter pub get
            flutter build apk --release
            
            
            
  
