name: build apk whenever main push
on:
  push:
    branches:
      - main

jobs:
  build_apk:
    env:
      KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
    name: "Build release apk"
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Using flutter version"
        uses: subosito/flutter-action@v2

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > export_keystore.jks
          echo "STORE_FILE=$(pwd)/export_keystore.jks" >> $GITHUB_ENV

      - name: "build apk release"
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
