
   # i dont know what i am doing 
name: build apk and add to github release
on: 
  workflow_dispatch:
    inputs:
      name: 
        description: "name of you"
        required: true
        type: string
      actions: 
        description: "this is an action"
        required: true
        type: choice
        options:
          - Action 1
          - Action 2
          - Action 3
          
jobs:  
  action:
      name: "choosing an action"
      runs-on:
        - ubuntu-latest
      steps:
        - name: "choosing an action"
          run: |
            echo "You are: ${{github.events.inputs.name}}"
            echo "You have choosed : ${{github.events.inputs.action}}"
            
            
  
